package qmk

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/elentok/qmkmd/internal/layout"
)

var mods = []string{"gui", "ctl", "alt", "sft"}

var simpleMappings = buildSimpleMappings()

var layerCommands = map[string]bool{
	"df":  true,
	"mo":  true,
	"osl": true,
	"tg":  true,
	"to":  true,
	"tt":  true,
}

func WriteQMKCode(parsed layout.Layout) ([]string, error) {
	lines := []string{
		"// This file has been auto-generated by qmkmd (https://github.com/elentok/qmkmd)",
	}
	lines = append(lines, writeQMKImportsCode(parsed)...)
	lines = append(lines, writeQMKLayersEnumCode(parsed)...)
	lines = append(lines, "")

	layerLines, err := writeQMKLayersCode(parsed)
	if err != nil {
		return nil, err
	}
	lines = append(lines, layerLines...)

	comboLines, err := WriteCombos(parsed)
	if err != nil {
		return nil, err
	}
	lines = append(lines, comboLines...)

	return lines, nil
}

func ExpandLayer(layerData layout.Layer, parsed layout.Layout) (layout.Layer, error) {
	rows := make([][]layout.LayerCell, 0, len(layerData.Rows))
	for rowIndex, row := range layerData.Rows {
		newRow := make([]layout.LayerCell, 0, len(row))
		for cellIndex, cell := range row {
			switch {
			case !cell.IsOccupied:
				newRow = append(newRow, layout.LayerCell{})
			case cell.Kind == layout.CellSeparator:
				newRow = append(newRow, layout.LayerCell{Kind: layout.CellSeparator, IsOccupied: true})
			default:
				mapping, err := ExpandMapping(cell.Mapping, parsed)
				if err != nil {
					return layout.Layer{}, &layout.LayerError{
						Msg:    err.Error(),
						Layer:  layerData,
						LineNr: layerData.RowToLine[rowIndex],
						Row:    rowIndex + 1,
						Col:    cellIndex + 1,
					}
				}
				if mapping == "" {
					return layout.Layer{}, &layout.LayerError{
						Msg:    fmt.Sprintf("Invalid mapping '%s", cell.Mapping),
						Layer:  layerData,
						LineNr: layerData.RowToLine[rowIndex],
						Row:    rowIndex + 1,
						Col:    cellIndex + 1,
					}
				}
				newRow = append(newRow, layout.LayerCell{Mapping: mapping, Kind: layout.CellKey, IsOccupied: true})
			}
		}
		rows = append(rows, newRow)
	}

	return layout.Layer{Name: layerData.Name, Rows: rows, RowToLine: layerData.RowToLine}, nil
}

func ExpandMapping(mapping string, parsed layout.Layout) (string, error) {
	if raw, ok := expandRaw(mapping); ok {
		return raw, nil
	}
	if simple, ok := expandSimpleMapping(mapping); ok {
		return simple, nil
	}
	if modTap, ok, err := expandModOrLayerTap(mapping, parsed); ok || err != nil {
		return modTap, err
	}
	if oneShot, ok, err := expandOneShotMod(mapping); ok || err != nil {
		return oneShot, err
	}
	if combo, ok, err := expandCombo(mapping); ok || err != nil {
		return combo, err
	}
	if layerCommand, ok, err := expandLayerCommand(mapping, parsed); ok || err != nil {
		return layerCommand, err
	}
	if alias, ok, err := expandAlias(mapping, parsed); ok || err != nil {
		return alias, err
	}
	return "", nil
}

func WriteCombos(parsed layout.Layout) ([]string, error) {
	if len(parsed.Combos) == 0 {
		return nil, nil
	}

	constLines := make([]string, 0, len(parsed.Combos))
	comboLines := make([]string, 0, len(parsed.Combos))

	for index, combo := range parsed.Combos {
		rawKeys := strings.Split(combo.Keys, "+")
		keys := make([]string, 0, len(rawKeys))
		for _, key := range rawKeys {
			expanded, err := ExpandMapping(key, parsed)
			if err != nil {
				return nil, err
			}
			keys = append(keys, expanded)
		}

		action, err := ExpandMapping(combo.Action, parsed)
		if err != nil {
			return nil, err
		}

		constName := "combo" + strconv.Itoa(index)
		constLines = append(constLines, fmt.Sprintf("const uint16_t PROGMEM %s[] = {%s, COMBO_END};", constName, strings.Join(keys, ", ")))
		comboLines = append(comboLines, fmt.Sprintf("  COMBO(%s, %s),", constName, action))
	}

	lines := append([]string{}, constLines...)
	lines = append(lines, "")
	lines = append(lines, fmt.Sprintf("combo_t key_combos[%d] = {", len(parsed.Combos)))
	lines = append(lines, comboLines...)
	lines = append(lines, "};")
	return lines, nil
}

func LayerQMKName(name string) string {
	return "L" + strings.ToUpper(name)
}

func writeQMKImportsCode(parsed layout.Layout) []string {
	lines := make([]string, 0, len(parsed.Options.Imports))
	for _, imp := range parsed.Options.Imports {
		lines = append(lines, fmt.Sprintf("#import %q", imp))
	}
	return lines
}

func writeQMKLayersEnumCode(parsed layout.Layout) []string {
	lines := []string{"enum layers {"}
	for index, layerData := range parsed.Layers {
		name := LayerQMKName(layerData.Name)
		if index == 0 {
			lines = append(lines, fmt.Sprintf("  %s = 0,", name))
		} else {
			lines = append(lines, fmt.Sprintf("  %s,", name))
		}
	}
	lines = append(lines, "};")
	return lines
}

func writeQMKLayersCode(parsed layout.Layout) ([]string, error) {
	expandedLayers := make([]layout.Layer, 0, len(parsed.Layers))
	for _, layerData := range parsed.Layers {
		expanded, err := ExpandLayer(layerData, parsed)
		if err != nil {
			return nil, err
		}
		expandedLayers = append(expandedLayers, expanded)
	}

	columnWidths := layout.CalcColumnWidths(expandedLayers)
	lines := []string{"const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {"}
	for _, expandedLayer := range expandedLayers {
		lines = append(lines, writeQMKLayerCode(expandedLayer, columnWidths, parsed)...)
	}
	lines = append(lines, "};")
	return lines, nil
}

func writeQMKLayerCode(expandedLayer layout.Layer, columnWidths []int, parsed layout.Layout) []string {
	lines := []string{fmt.Sprintf("  [%s] = %s(", LayerQMKName(expandedLayer.Name), parsed.Options.LayoutFn)}

	for rowIndex := range parsed.Structure.Rows {
		rowParts := make([]string, 0, len(parsed.Structure.Rows[rowIndex]))
		for colIndex := range parsed.Structure.Rows[rowIndex] {
			cell := expandedLayer.Rows[rowIndex][colIndex]
			colWidth := columnWidths[colIndex] + 1

			switch {
			case cell.Kind == layout.CellSeparator:
				rowParts = append(rowParts, " /* || */ ")
			case !cell.IsOccupied:
				rowParts = append(rowParts, padEnd("", colWidth))
			default:
				rowParts = append(rowParts, padEnd(cell.Mapping+",", colWidth))
			}
		}
		lines = append(lines, "    "+strings.TrimRight(strings.Join(rowParts, " "), " "))
	}

	last := lines[len(lines)-1]
	lines[len(lines)-1] = strings.TrimSuffix(last, ",")
	lines = append(lines, "  ),")
	return lines
}

func expandSimpleMapping(mapping string) (string, bool) {
	value, ok := simpleMappings[mapping]
	return value, ok
}

func expandModOrLayerTap(mapping string, parsed layout.Layout) (string, bool, error) {
	if !strings.Contains(mapping, "/") {
		return "", false, nil
	}

	parts := strings.Split(mapping, "/")
	if len(parts) != 2 {
		return "", true, nil
	}
	hold, tap := parts[0], parts[1]
	qmkTap, err := ExpandMapping(tap, parsed)
	if err != nil {
		return "", true, err
	}
	if qmkTap == "" {
		return "", true, nil
	}
	if isValidMod(hold) {
		return strings.ToUpper(hold) + "_T(" + qmkTap + ")", true, nil
	}

	if matches := layerFuncMatch(hold); len(matches) == 2 {
		if matches[0] == "l" {
			layerName := matches[1]
			if hasLayer(parsed, layerName) {
				return fmt.Sprintf("LT(%s, %s)", LayerQMKName(layerName), qmkTap), true, nil
			}
			return "", true, fmt.Errorf("Mapping %s refers to a non-existing layer '%s'", mapping, layerName)
		}
		return "", true, fmt.Errorf("Mapping '%s' uses an invalid function '%s'", mapping, matches[0])
	}

	return "", true, nil
}

func expandOneShotMod(mapping string) (string, bool, error) {
	if !strings.HasPrefix(mapping, "osm(") || !strings.HasSuffix(mapping, ")") {
		return "", false, nil
	}
	mod := strings.TrimSuffix(strings.TrimPrefix(mapping, "osm("), ")")
	if !isValidMod(mod) {
		return "", true, fmt.Errorf("OneShotMod '%s' has invalid mod '%s'", mapping, mod)
	}
	return "OSM(MOD_" + strings.ToUpper(mod) + ")", true, nil
}

func expandLayerCommand(mapping string, parsed layout.Layout) (string, bool, error) {
	matches := layerFuncMatch(mapping)
	if len(matches) != 2 {
		return "", false, nil
	}
	command, layerName := matches[0], matches[1]
	if !layerCommands[command] {
		return "", true, fmt.Errorf("Invalid layer command '%s'", command)
	}
	if !hasLayer(parsed, layerName) {
		return "", true, fmt.Errorf("Layer command '%s' refers to non-existing layer '%s'", mapping, layerName)
	}
	return strings.ToUpper(command) + "(" + LayerQMKName(layerName) + ")", true, nil
}

func expandCombo(mapping string) (string, bool, error) {
	if !strings.Contains(mapping, "+") {
		return "", false, nil
	}

	rawParts := strings.Split(mapping, "+")
	parts := make([]string, 0, len(rawParts))
	for index, part := range rawParts {
		isLast := index >= len(rawParts)-1
		if !isLast {
			if fullMod, ok := expandShortMod(part); ok {
				parts = append(parts, "L"+strings.ToUpper(fullMod))
				continue
			}
		}

		expanded, ok := expandSimpleMapping(part)
		if !ok {
			return "", true, fmt.Errorf("Unable to expand '%s'", part)
		}
		parts = append(parts, expanded)
	}
	return wrapInParens(parts, 0), true, nil
}

func expandAlias(mapping string, parsed layout.Layout) (string, bool, error) {
	if len(parsed.Aliases) == 0 {
		return "", false, nil
	}
	alias, ok := parsed.Aliases[mapping]
	if !ok {
		return "", false, nil
	}
	expanded, err := ExpandMapping(alias.Value, parsed)
	return expanded, true, err
}

func wrapInParens(parts []string, index int) string {
	isLast := index >= len(parts)-1
	next := ""
	if !isLast {
		next = "(" + wrapInParens(parts, index+1) + ")"
	}
	return parts[index] + next
}

func hasLayer(parsed layout.Layout, name string) bool {
	for _, layerData := range parsed.Layers {
		if layerData.Name == name {
			return true
		}
	}
	return false
}

func expandRaw(mapping string) (string, bool) {
	if !strings.HasPrefix(mapping, "raw(") || !strings.HasSuffix(mapping, ")") {
		return "", false
	}
	return strings.TrimSuffix(strings.TrimPrefix(mapping, "raw("), ")"), true
}

func expandShortMod(shortMod string) (string, bool) {
	shortMods := []string{"g", "c", "a", "s"}
	for index, value := range shortMods {
		if value == shortMod {
			return mods[index], true
		}
	}
	return "", false
}

func isValidMod(text string) bool {
	if len(text) < 2 {
		return false
	}
	if text[0] != 'l' && text[0] != 'r' {
		return false
	}
	for _, mod := range mods {
		if text[1:] == mod {
			return true
		}
	}
	return false
}

func layerFuncMatch(value string) []string {
	start := strings.Index(value, "(")
	end := strings.LastIndex(value, ")")
	if start <= 0 || end <= start+1 {
		return nil
	}
	return []string{value[:start], value[start+1 : end]}
}

func buildSimpleMappings() map[string]string {
	keys := []string{
		"esc", "tab", "left", "down", "up", "right", "ent", "home", "pgup", "pgdn",
		"end", "spc", "del", "wbak", "wfwd", "pscr",
	}
	for _, c := range "abcdefghijklmnopqrstuvwxyz0123456789" {
		keys = append(keys, string(c))
	}
	for i := 1; i < 13; i++ {
		keys = append(keys, "f"+strconv.Itoa(i))
	}

	values := map[string]string{
		"'":     "KC_QUOT",
		"quot":  "KC_QUOT",
		"\"":    "KC_DQUO",
		",":     "KC_COMM",
		".":     "KC_DOT",
		"bs":    "KC_BSPC",
		"`":     "KC_GRV",
		":":     "KC_COLN",
		";":     "KC_SCLN",
		"[":     "KC_LBRC",
		"]":     "KC_RBRC",
		"<":     "KC_LABK",
		">":     "KC_RABK",
		"{":     "KC_LCBR",
		"}":     "KC_RCBR",
		"(":     "KC_LPRN",
		")":     "KC_RPRN",
		"~":     "KC_TILD",
		"=":     "KC_EQL",
		"-":     "KC_MINS",
		"+":     "KC_PLUS",
		"_":     "KC_UNDS",
		"|":     "KC_PIPE",
		"/":     "KC_SLSH",
		"\\":    "KC_BSLS",
		"?":     "KC_QUES",
		"!":     "KC_EXLM",
		"@":     "KC_AT",
		"#":     "KC_HASH",
		"$":     "KC_DLR",
		"%":     "KC_PERC",
		"^":     "KC_CIRC",
		"&":     "KC_AMPR",
		"*":     "KC_ASTR",
		"copy":  "KC_COPY",
		"paste": "KC_PSTE",
		"boot":  "QK_BOOT",
		"play":  "KC_MPLY",
		"vol+":  "KC_VOLU",
		"vol-":  "KC_VOLD",
		"__":    "_______",
	}
	for _, key := range keys {
		values[key] = "KC_" + strings.ToUpper(key)
	}
	for _, mod := range mods {
		values["l"+mod] = "KC_L" + strings.ToUpper(mod)
		values["r"+mod] = "KC_R" + strings.ToUpper(mod)
	}
	return values
}

func padEnd(value string, width int) string {
	if len(value) >= width {
		return value
	}
	return value + strings.Repeat(" ", width-len(value))
}
