import { calcColumnWidths, layerQmkName } from "./layer.ts"
import { expandLayer } from "./expand-layer.ts"
import { Layout } from "./types.ts"

export function writeQmkCode(layout: Layout): string[] {
  const { options: o, structure: s } = layout

  const lines = [
    "// This file has been auto-generated by qmkmd (https://github.com/elentok/qmkmd)",
    "enum layers {",
    ...layout.layers.map((layer, index) => {
      const qmkName = layerQmkName(layer.name)
      return (index === 0) ? `  ${qmkName} = 0,` : `  ${qmkName},`
    }),
    "};",
    "",
    "const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {",
  ]

  const expandedLayers = layout.layers.map((layer) => expandLayer(layer, layout))
  const columnWidths = calcColumnWidths(expandedLayers)

  for (const layer of expandedLayers) {
    lines.push(`  [${layerQmkName(layer.name)}] = ${o.layoutFn}(`)

    for (let rowIndex = 0; rowIndex < s.rows.length; rowIndex++) {
      const row = s.rows[rowIndex]

      const rowParts: string[] = []

      for (let colIndex = 0; colIndex < row.length; colIndex++) {
        const cell = layer.rows[rowIndex][colIndex]
        const colWidth = columnWidths[colIndex] + 1

        if (cell === "separator") {
          rowParts.push(" /* || */ ")
        } else if (cell == null) {
          rowParts.push("".padEnd(colWidth))
        } else {
          rowParts.push(`${cell.mapping},`.padEnd(colWidth))
        }
      }

      const line = "    " + rowParts.join(" ").trimEnd()
      lines.push(line)
    }

    lines[lines.length - 1] = lines[lines.length - 1].replace(/,$/, "")

    lines.push("  ),")
  }

  lines.push("};")
  return lines
}
