# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - binary: qmkmd
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

homebrew_casks:
  - name: qmkmd
    binaries: [qmkmd]
    url:
      template: "https://github.com/elentok/qmkmd/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Casks
    homepage: "https://github.com/elentok/qmkmd"
    description: "Build, format, and copy QMK keyboard layouts written in Markdown."
    skip_upload: auto
    hooks:
      post:
        install: |
          if OS.mac?
            if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
              system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qmkmd"]
            end
          end
    repository:
      owner: elentok
      name: homebrew-stuff
      token: "{{ .Env.GORELEASER_HOMEBREW_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
